workspace = { members = ["borrow", "borrow_me_the_reference", "copy", "counting_words", "doubtful", "inv_pyramid", "modify_letter",  "name_initials", "ownership", "parts_sums", "smallest", "string_literals", "tic_tac_toe", "to_url"] }
[package]
name = "piscine-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
scalar = {path="scalar"}
temperature_conv = {path="temperature_conv"}
find_factorial = {path="find_factorial"}
matrix_transposition = {path= "matrix_transposition"}
borrow = {path ="borrow"}
