workspace = { members = ["borrow", "borrow_me_the_reference", "copy", "doubtful", "name_initials", "ownership", "string_literals", "tic_tac_toe", "to_url"] }
[package]
name = "piscine-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
scalar = {path="scalar"}
temperature_conv = {path="temperature_conv"}
find_factorial = {path="find_factorial"}
matrix_transposition = {path= "matrix_transposition"}
borrow = {path ="borrow"}
